name: CI

on:
  push:
    branches: ["master"]

jobs:
  build-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: rom-name-finder/package-lock.json
      - run: |
          cd rom-name-finder
          npm ci
          npm run db

  lint:
    runs-on: ubuntu-latest
    needs: build-db
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: rom-name-finder/frontend/package-lock.json
      - run: |
          cd rom-name-finder/frontend
          npm ci
          npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: rom-name-finder/frontend/package-lock.json
      - run: |
          cd rom-name-finder/frontend
          npm ci
          npm run test:run

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: rom-name-finder/frontend/package-lock.json
      - run: |
          cd rom-name-finder/frontend
          npm ci
          npm run build
