name: CI

env:
  NODE_VERSION: 22
  WDIR: rom-name-finder
  FE_WDIR: rom-name-finder/frontend

on:
  push:
    branches: ["master"]

jobs:
  build-db:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory:  ${{ env.WDIR }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.WDIR }}/package-lock.json
      - run: npm ci
      - run: npm run db

  lint:
    runs-on: ubuntu-latest
    needs: build-db
    defaults:
      run:
        working-directory: ${{ env.FE_WDIR }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.FE_WDIR }}/package-lock.json
      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    defaults:
      run:
        working-directory: ${{ env.FE_WDIR }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.FE_WDIR }}/package-lock.json
      - run: npm ci
      - run: npm run test:run

  build:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: ${{ env.FE_WDIR }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.FE_WDIR }}/package-lock.json
      - run: npm ci
      - run: npm run build
