name: Deploy to GitHub Pages

env:
  NODE_VERSION: 22
  WDIR: rom-name-finder
  FE_WDIR: rom-name-finder/frontend
  ARTIFACT_NAME: dist

on:
  push:
    branches: ["release"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-rom-name-finder-db:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    defaults:
      run:
        working-directory:  ${{ env.WDIR }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.WDIR }}/package-lock.json
      - run: npm ci
      - run: npm run db
      - uses: actions/upload-artifact@v5
        with:
          name: db
          path: ./${{ env.FE_WDIR }}/${{ env.ARTIFACT_NAME }}/db

  build-rom-name-finder-node:
    runs-on: ubuntu-latest
    needs: build-rom-name-finder-db
    defaults:
      run:
        working-directory: ${{ env.FE_WDIR }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.FE_WDIR }}/package-lock.json
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v5
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./${{ env.FE_WDIR }}/${{ env.ARTIFACT_NAME }}

  upload-cover-3d:
    runs-on: ubuntu-latest
    needs: build-rom-name-finder-db
    steps:
      - uses: actions/checkout@v5
      - uses: actions/upload-artifact@v5
        with:
          name: cover_3d
          path: ./cover_3d/src
      
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build-rom-name-finder-node, upload-cover-3d]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/configure-pages@v5
      - uses: actions/download-artifact@v5
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./rom-name-finder/
      - uses: actions/download-artifact@v5
        with:
          name: db
          path: ./rom-name-finder/db
      - uses: actions/download-artifact@v5
        with:
          name: cover_3d
          path: ./game-box-3d
      - uses: actions/upload-pages-artifact@v4
        with:
          path: ./
      - uses: actions/deploy-pages@v4
        id: deployment